# Generated by Django 4.2.11 on 2025-07-04 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedimage',
            name='file_name',
            field=models.ImageField(upload_to='generated_images/'),
        ),
    ]
