# Generated by Django 5.2.4 on 2025-08-15 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='daily_generations',
            new_name='generations_today',
        ),
    ]
