services:
  - type: web
    name: django-backend
    env: python
    rootDir: backend
    buildCommand: cd backend pip install -r requirements.txt
    startCommand: gunicorn backend.wsgi:application
    envVars:
      - key: DJANGO_SECRET_KEY
        value: ${DJANGO_SECRET_KEY}
      - key: DEBUG
        value: "False"
      - key: CLOUDINARY_URL
        value: ${CLOUDINARY_URL}
      - key: DATABASE_URL
        fromDatabase:
          name: your-neon-db-name
          property: connectionString

  - type: web
    name: react-frontend
    env: static
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
